# Generated by MathModel Skill scaffold generator.
from __future__ import annotations

from result_contract_io import run_question_scaffold


QUESTION = {
  "question_id": "Q2",
  "title": "问题二",
  "task_type": "综合建模/统计分析",
  "core_goal": "利用无人机FY1 投放1 枚烟幕干扰弹实施对M1 的干扰，确定FY1 的飞行方",
  "baseline_model": "描述统计、相关性分析或可解释基线模型",
  "main_model": "结合题目目标选择回归、评价、优化或仿真模型",
  "backup_models": [
    "可解释统计模型",
    "稳健性对照模型"
  ],
  "model_reason": "该问属于“综合建模/统计分析”任务，结合题目目标选择回归、评价、优化或仿真模型 能在保留可解释性的同时承接题目约束：问题2 利用无人机FY1 投放1 枚烟幕干扰弹实施对M1 的干扰，确定FY1 的飞行方。",
  "formula_requirements": [
    "定义输入变量与输出目标",
    "说明核心模型函数或目标函数",
    "给出评价指标与检验方式"
  ],
  "validation": [
    "结果复核",
    "敏感性分析",
    "与题意约束对照"
  ],
  "figures": [
    {
      "figure_id": "fig_q2_1",
      "title": "数据概览图",
      "purpose": "支撑Q2的模型结果、验证或敏感性分析",
      "expected_path": "paper_output/figures/fig_q2_1.png"
    },
    {
      "figure_id": "fig_q2_2",
      "title": "结果对比图",
      "purpose": "支撑Q2的模型结果、验证或敏感性分析",
      "expected_path": "paper_output/figures/fig_q2_2.png"
    },
    {
      "figure_id": "fig_q2_3",
      "title": "敏感性分析图",
      "purpose": "支撑Q2的模型结果、验证或敏感性分析",
      "expected_path": "paper_output/figures/fig_q2_3.png"
    }
  ],
  "paper_sections": [
    "问题二模型建立",
    "问题二结果分析",
    "问题二模型检验"
  ]
}


if __name__ == "__main__":
    raise SystemExit(run_question_scaffold(QUESTION))
